# Generated by Django 4.2.4 on 2023-10-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=30)),
                ('club', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=30)),
            ],
        ),
    ]
